"""add fingerprints table

Revision ID: 9b9719c06475
Revises: a24834d38769
Create Date: 2026-06-14 23:52:15.292909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9719c06475'
down_revision: Union[str, Sequence[str], None] = 'a24834d38769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fingerprints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('confidence_histogram', sa.JSON(), nullable=False),
    sa.Column('entropy', sa.Float(), nullable=False),
    sa.Column('uncertainty_rate', sa.Float(), nullable=False),
    sa.Column('class_bias', sa.Float(), nullable=False),
    sa.Column('mean_confidence', sa.Float(), nullable=False),
    sa.Column('confidence_std', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['probe_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fingerprints')
    # ### end Alembic commands ###
