"""create behavioral fingerprints table

Revision ID: 83d7863592ab
Revises: f849f18115e4
Create Date: 2026-06-12 18:17:21.898064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d7863592ab'
down_revision: Union[str, Sequence[str], None] = 'f849f18115e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavioral_fingerprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('num_samples', sa.Integer(), nullable=False),
    sa.Column('class_distribution', sa.JSON(), nullable=False),
    sa.Column('confidence_distribution', sa.JSON(), nullable=False),
    sa.Column('high_uncertainty_regions', sa.JSON(), nullable=False),
    sa.Column('boundary_samples', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['registered_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_fingerprints_model_id'), 'behavioral_fingerprints', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavioral_fingerprints_model_id'), table_name='behavioral_fingerprints')
    op.drop_table('behavioral_fingerprints')
    # ### end Alembic commands ###
